name: current_gcp_project
description: A helper to determine the current GCP project your code is running on.
version: 0.0.2
homepage: https://github.com/Morel-Tech/current_gcp_project

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  http: ^1.0.0
  platform: ^3.1.0

dev_dependencies:
  mocktail: ^1.0.1
  test: ^1.19.2
  very_good_analysis: ^5.1.0
